CREATE TABLE user (id INTEGER PRIMARY KEY, name VARCHAR(50));
CREATE TABLE todo (id INTEGER PRIMARY KEY, task VARCHAR(100), user_id INTEGER);

ALTER TABLE todo ADD FOREIGN KEY (user_id) REFERENCES user(id);