INSERT INTO userdata VALUES (1, 'Jane');
INSERT INTO userdata VALUES (2, 'John');
INSERT INTO userdata VALUES (3, 'Dave');
INSERT INTO userdata VALUES (4, 'Emma');
INSERT INTO userdata VALUES (5, 'Robert');
INSERT INTO todo VALUES (1, 'Setup pgAdmin', 2);
INSERT INTO todo VALUES (2, 'Download Git', 2);
INSERT INTO todo VALUES (3, 'Setup VS Code', 1, TRUE);
INSERT INTO todo VALUES (4, 'Download PostgreSQL', 2);
INSERT INTO todo VALUES (5, 'Install server', 2);
INSERT INTO todo VALUES (6, 'Create superuser', 2);
INSERT INTO todo VALUES (7, 'Create database', 2);
INSERT INTO todo VALUES (8, 'Create tables', 2);
INSERT INTO todo VALUES (9, 'Wash the dishes', 3);
INSERT INTO todo VALUES (10, 'Read the PostgreSQL manual', 4);
INSERT INTO todo VALUES (11, 'Exercise', 3);
INSERT INTO todo VALUES (12, 'Wake up in time!', 5, TRUE);
INSERT INTO todo VALUES (13, 'Go to the gym', 3);
INSERT INTO todo VALUES (14, 'Wash the dishes', 5, TRUE);